name: Review
on:
  push:
  pull_request:
jobs:
  linter_name:
    name: runner / Linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-check' || 'github-check' }}
          # Change reporter level if you need.
          level: info
